{application, erlycomet,
  [
    {description, "Erlang Comet Server"},
    {vsn, "0.1"},
    {modules, [erlycomet_app,
                erlycomet,
                erlycomet_sup,
                erlycomet_request,
                erlycomet_ets_store]},
    {registered, []},
    {applications, [kernel,
                    stdlib,
                    crypto]},
    {env, []},
    {mod, {erlycomet_app, []}} ]}.
